### ISSUE TITLE
Move slider to "Night Light On" submenu

### ISSUE THREAD

**Issue by hackel** [TimurKiyivinski/gnome-shell-night-light-slider-extension#22]
Would it be possible to move the slider to the "Night Light On" submenu, so that the slider was only visible when this menu is expanded?  Changing the colour temperature is something I can't imagine doing very often, so I really don't need to have the slider displayed all the time.

**Comment by kiyui** [comment]
Note to self:
Main blocker to implementing this is not knowing how to get the instance of the night light submenu, especially without interfering with other extensions.

May need to find other extensions that perform likewise behaviour to see how they do it.

**Comment by tomellor** [comment]
The function to add into the night light menu would be `Main.panel.statusArea.aggregateMenu._nightLight.menu._getMenuItems()[0].menu.addMenuItem()`

**Comment by kiyui** [comment]
Thanks a bunch, @tomellor ! @hackel please check out the ZIP at #29 and see if this is about what you wanted :grin:

**Comment by tomellor** [comment]
Cool! How does updating the available version on extensions.gnome.org work? When will we see the "official" update I mean

**Comment by kiyui** [comment]
Hi @tomellor , you basically just submit the updated ZIP for the release and wait for a review before it gets pushed and people can officially download it. The version currently published is `7.0` and I've been waiting for a review for `8.0` since April, with the latest version now being `10.0` :crying_cat_face: 

Not quite sure however how we can go about helping GNOME with reviewing other extensions, so things go out quicker.

**Comment by tomellor** [comment]
Yeah I ask because I've seen you had more versions since 7. I have some interest in doing more of an overhaul to this Night Light menu in general, maybe I'll make a bug to talk about my ideas there and provide some relevant code.

Shame that the review process takes a long time, perhaps that's why some other extensions I use are not doing so well with new versions of GNOME.
