### ISSUE TITLE
dual monitors

### ISSUE THREAD

**Issue by scotticles** [TimurKiyivinski/gnome-shell-night-light-slider-extension#30]
Ubuntu 18.04 / nvidia 390
It works but its only working on my second monitor and not my primary...not sure if anyone else has seen this.

**Comment by kiyui** [comment]
Hi, I don't think this issue is related to this extension as this extension simply adds a slider to control the night light temperature as provided by GNOME. If you can reproduce this issue and narrow it down as to being caused by this extension, please feel free to reopen the issue. I am personally using it on multiple dual-screen setups.
