### ISSUE TITLE
Extension stop working on Ubuntu 19.10 dev branch with gnome 3.34

### ISSUE THREAD

**Issue by foer** [TimurKiyivinski/gnome-shell-night-light-slider-extension#48]
**Describe the bug**
The extension stops working in Ubuntu 19.10/gnome 3.34. The error message is:

`Error: No signal 'value-changed' on object 'Gjs_Slider'`

**System Information:**
- OS: Ubuntu 19.10 development branch
- GNOME Version: 3.34

**Comment by CircleCode** [comment]
it seems to be the same error than https://github.com/aleho/gnome-shell-volume-mixer/issues/102 with the fix in https://github.com/aleho/gnome-shell-volume-mixer/commit/5ec18540eaa53345d545cef6dfd343d4a8b0db55

**Comment by kiyui** [comment]
This should be fixed now, you can try out from [the release page](https://github.com/kiyui/gnome-shell-night-light-slider-extension/releases/tag/12.0).

I will revisit updating the version on the GNOME extension website, because I cannot currently log in despite having reset my password 3 times. Sorry for the inconvenience.

**Comment by stuartpb** [comment]
Still working on getting this published?

**Comment by kiyui** [comment]
Hi @stuartpb, I've tried resetting my password multiple times and still am not able to get in. It's quite the nuisance. Admittedly I haven't gone on to IRC or forums to see if anyone else is facing this issue, because I really haven't had the time.

Perhaps someone with an account that can log in could comment on the extension and lead them here momentarily or help look into it. I'm really sorry for the inconvenience :bowing_woman:
